### ISSUE TITLE
Working with Ubuntu 20.04 Ryzen 5 3550H/Nvidia GTX 1650

### ISSUE THREAD

**Issue by mindslost** [dglt1/optimus-switch-amd-sddm#2]
I can confirm this works on my Asus Tuf Gaming FX505DT laptop. There is some flickering on the laptop display when in nvidia mode. HDMI output works just fine.

**Comment by sticsk** [comment]
I have the same laptop, by any mean do you use optimus-manager?

**Comment by mindslost** [comment]
> I have the same laptop, by any mean do you use optimus-manager?

I do not.

**Comment by spantheslayer** [comment]
@mindslost  did u try with manjaro latest  ?
